#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2020-2024 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

NODE_VERSION=$(node -v)
NPM_VERSION=$(npm -v)

if [[ ! "$NODE_VERSION" =~ ^v(18|20|22)[.].*$ ]]; then
  echo "Node version $NODE_VERSION not supported. Only Node 18.x, 20.x and 22.x are supported"
  exit 1
fi

if [[ ! "$NPM_VERSION" =~ ^(9|10)[.].*$ ]]; then
  echo "npm version $NPM_VERSION not supported. Only npm 9.x and 10.x are supported"
  exit 1
fi

rm -rf node_modules
rm -rf node_modules_global
