#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2022 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${SCRIPT_DIR}/../../modules/org.openbravo.client.kernel/jsutils/dir-functions

OPENBRAVO_ROOT_PATH=$(getOpenbravoRootPath 2>/dev/null)

if [[ -z "${OPENBRAVO_ROOT_PATH}" ]]; then
    exit 0
fi

IS_A_MODULE=$(isCurrentFolderModuleRoot)

echo "pre-commit: Verifying if src folders are instrumented"

if [ $(find . -type f | grep "/.instrumented") ]; then
  echo -e "src folders are instrumented, please undo instrumentation before commiting.\nTo do so, from modules/{module}/web-jspack/{module} execute: 
  npm run clean-code \nAborting commit..."
  exit 1
fi 
